### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by ArtificialZeng** [Nikhil-Kasukurthi/Counting-people-video#15]
Traceback (most recent call last):
  File "object_detect.py", line 118, in <module>
    feed_dict={image_tensor: image_np_expanded})
  File "/home/dhqt/Anaconda3/envs/peopleCountingVideo/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/dhqt/Anaconda3/envs/peopleCountingVideo/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/dhqt/Anaconda3/envs/peopleCountingVideo/lib/python3.5/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ArtificialZeng** [comment]
don't you have requirements.txt?
